/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_artwork_kalakruti_skiadraw_SkiaGLRenderer */

#ifndef _Included_com_artwork_kalakruti_skiadraw_SkiaGLRenderer
#define _Included_com_artwork_kalakruti_skiadraw_SkiaGLRenderer
#ifdef __cplusplus
extern "C" {
#endif
#undef com_artwork_kalakruti_skiadraw_SkiaGLRenderer_STROKE_WIDTH
#define com_artwork_kalakruti_skiadraw_SkiaGLRenderer_STROKE_WIDTH 5L
/*
 * Class:     com_artwork_kalakruti_skiadraw_SkiaGLRenderer
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artwork_kalakruti_skiadraw_SkiaGLRenderer_init
        (JNIEnv *, jclass);

/*
 * Class:     com_artwork_kalakruti_skiadraw_SkiaGLRenderer
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artwork_kalakruti_skiadraw_SkiaGLRenderer_destroy
        (JNIEnv *, jclass);

/*
 * Class:     com_artwork_kalakruti_skiadraw_SkiaGLRenderer
 * Method:    setSize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_artwork_kalakruti_skiadraw_SkiaGLRenderer_setSize
        (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_artwork_kalakruti_skiadraw_SkiaGLRenderer
 * Method:    draw
 * Signature: (Lcom/artwork/kalakruti/skiadraw/SkiaPath;FFFF)V
 */
JNIEXPORT void JNICALL Java_com_artwork_kalakruti_skiadraw_SkiaGLRenderer_draw
        (JNIEnv *, jclass, jobject, jfloat, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
