/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_artwork_kalakruti_skiadraw_SkiaPath */

#ifndef _Included_com_artwork_kalakruti_skiadraw_SkiaPath
#define _Included_com_artwork_kalakruti_skiadraw_SkiaPath
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_artwork_kalakruti_skiadraw_SkiaPath
 * Method:    init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_artwork_kalakruti_skiadraw_SkiaPath_init
        (JNIEnv *, jclass);

/*
 * Class:     com_artwork_kalakruti_skiadraw_SkiaPath
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_artwork_kalakruti_skiadraw_SkiaPath_destroy
        (JNIEnv *, jobject);

/*
 * Class:     com_artwork_kalakruti_skiadraw_SkiaPath
 * Method:    moveTo
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_artwork_kalakruti_skiadraw_SkiaPath_moveTo
        (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_artwork_kalakruti_skiadraw_SkiaPath
 * Method:    lineTo
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_artwork_kalakruti_skiadraw_SkiaPath_lineTo
        (JNIEnv *, jobject, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
